### PR TITLE
Update AVS headers and copy frame properties for AVS+ and VS

### PR DESCRIPTION
**Pull request by realfinder**
based on Asd-g changes https://github.com/HomeOfAviSynthPlusEvolution/neo_f3kdb/pull/10

### CODE REVIEW

**Comment by realfinder** [comment]
and if they are ok (I did test and seems work) here the uptodate files of include [include.zip](https://github.com/HomeOfAviSynthPlusEvolution/neo_DFTTest/files/6564652/include.zip) to easily apply them on others

**Comment by kedaitinh12** [comment]
Can you pull request it to neo-fft3d?? I think neo-fft3d same error with neo-dfttest

**Comment by realfinder** [comment]
@kedaitinh12 maybe later

**Comment by kedaitinh12** [comment]
Thanks

**Pull request merged**
